version: "3.9"

services:
  moodledb: 
    image: postgres:15
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: "m@0dl3ing"
      POSTGRES_DB: moodle
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U moodle -d moodle"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgbouncer:
    image: pgbouncer/pgbouncer:1.15.0
    depends_on:
      moodledb:
        condition: service_healthy
    environment:
      # --- Variáveis RESTAURADAS (para parar o crash) ---
      DATABASES_HOST: moodledb
      DATABASES_PORT: 5432
      DATABASES_USER: moodle
      DATABASES_PASSWORD: "m@0dl3ing"
      DATABASES_DB: moodle
      USER: moodle         # Usuário para o Moodle se conectar ao PgBouncer
      PASSWORD: "m@0dl3ing" # Senha para o Moodle se conectar ao PgBouncer
      AUTH_TYPE: plain
      POOL_MODE: transaction
      PGBOUNCER_PORT: 6432
      
      # --- A CORREÇÃO DEFINITIVA ---
      # Esta variável injeta nossa correção no pgbouncer.ini gerado
      PGBOUNCER_IGNORE_STARTUP_PARAMETERS: options
      
    # --- REMOVA OS VOLUMES DOS ARQUIVOS DE CONFIGURAÇÃO ---
    # O script de entrada agora irá gerar o pgbouncer.ini e o userlist.txt
    # usando as variáveis de ambiente acima.
    volumes: [] 
    
    ports:
      - "6432:6432"
    restart: unless-stopped

  moodleapp:
    image: moodlehq/moodle-php-apache:8.3
    container_name: moodleapp
    depends_on:
      - pgbouncer
    environment:
      MOODLE_DOCKER_WEB_PORT: 8080
      MOODLE_DOCKER_WEB_HOST: localhost
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: "m@0dl3ing"
      MOODLE_DOCKER_DBTYPE: pgsql
      MOODLE_DOCKER_DBHOST: pgbouncer
      MOODLE_DOCKER_DBPORT: 6432
    volumes:
      - ./moodle_code:/var/www/html
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - moodle_data_vol:/var/www/moodledata
    entrypoint: /bin/bash -c "chown -R www-data:www-data /var/www/html /var/www/moodledata && chmod -R 770 /var/www/moodledata && apache2-foreground"
    restart: unless-stopped
    user: "www-data"

  haproxy:
    image: haproxy:latest
    depends_on:
      - moodleapp
    ports:
      - "8080:80"
    volumes:
      - ./haproxy_config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    restart: unless-stopped

volumes:
  pg_data:
  moodle_data_vol:
